### ISSUE TITLE
[FEATURE] Air compressor and turbine icons

### ISSUE THREAD

**Issue by nabily-met** [Metroscope-dev/metroscope-modeling-library#388]
### What is your precise need ?
Both icons are exactly the same beside the second power connector if the turbine (which will probably be removed later)
### What solution do you see ?
Change the icons: usually, the compressor in a gas turbine has much more stages compared to the turbine, therefore, we can create an icon that stretches horizontally for the compressor, and vertically for the turbine

**Comment by pierre-eliep-met** [comment]
![image](https://github.com/Metroscope-dev/metroscope-modeling-library/assets/97044708/e0889c60-dad0-48dc-a4ae-656f94e16fb0)

Fixed by #434
