### ISSUE TITLE
[FEATURE] Add option to calculate the nominal temperature rise/fall

### ISSUE THREAD

**Issue by moritzn-met** [Metroscope-dev/metroscope-modeling-library#458]
### What is your precise need ?
To set the `nominal_cold_side_temperature_rise ` and `nominal_hot_side_temperature_drop` for the flue gas HEX can be a challenge. Sometimes we dont have HMBD information about this. So it would be good to add an option to direct calculate it e.g. like this:
`HEX.nominal_cold_side_temperature_rise = HEX.T_hot_in - HEX.T_cold_in;`
`HEX.nominal_hot_side_temperature_drop = HEX.T_hot_in - HEX.T_cold_in;`

### What solution do you see ?
Add a parameter to the HEX components to decide if we want to set the nominal deltaT or calculate it.

**Comment by pierre-eliep-met** [comment]
Agreed, I think it should even be the default behaviour, and not with a parameter, and we should remove the `nominal` if I'm correct, the interest is the current `deltaT` not the nominal one

**Comment by pierre-eliep-met** [comment]
@nabily-met do you agree on this last point ?

**Comment by nabily-met** [comment]
@pierre-eliep-met the current deltaT will create a calculation loop, because it depends on the Cp, and if we use the actual delta, the Cp will also depend on it 😵
